"""Shared configuration names and this repository's Sentry identity."""

SENTRY_DSN_ENV_NAME_STR = "SENTRY_DSN"
SENTRY_ENVIRONMENT_ENV_NAME_STR = "SENTRY_ENVIRONMENT"
SENTRY_RELEASE_ENV_NAME_STR = "SENTRY_RELEASE"
SENTRY_LOG_LEVEL_ENV_NAME_STR = "SENTRY_LOG_LEVEL"
SENTRY_REPOSITORY_NAME_STR = "n-user-agent"
SENTRY_DEFAULT_ENVIRONMENT_STR = "development"
SENTRY_DEFAULT_LOG_LEVEL_STR = "INFO"
